version: "3.8"
services:
  backend:
    build:
      context: ..
      dockerfile: development/backend-${target}/ci.dockerfile
    environment:
      MYSQL_HOST: mysql-backend
      MYSQL_PORT: 3306
      MYSQL_DATABASE: isucondition
      MYSQL_USER: isucon
      MYSQL_PASSWORD: isucon
      ISU_CONDITION_IP: backend
    ports:
      - "3000:3000"
    volumes:
      - "../webapp/ec256-public.pem:/webapp/ec256-public.pem"
      - "../webapp/NoImage.png:/webapp/NoImage.png"
      - "../webapp/sql:/webapp/sql"
    depends_on:
      - mysql-backend

  mysql-backend:
    image: mariadb:10.6.2-focal
    restart: always
    environment:
      MYSQL_DATABASE: isucondition
      MYSQL_USER: isucon
      MYSQL_PASSWORD: isucon
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - "../webapp/sql/0_Schema.sql:/docker-entrypoint-initdb.d/0_Schema.sql"
    expose:
      - "3306"
    ports:
      - "3306:3306"

  apitest:
    build:
      context: ..
      dockerfile: development/apitest/ci.dockerfile
    environment:
      ISUXBENCH_TARGET: backend:3000
    entrypoint: dockerize -wait http://backend:3000 -timeout 60s
    command: ["/bench", "--no-load", "--exit-status"]
    volumes:
      - "../bench/data:/data"
      - "../bench/images:/images"
      - "../bench/key:/key"
    depends_on:
      - mysql-backend
      - backend
